### ISSUE TITLE
Update Services - Physical Therapy

### ISSUE THREAD

**Issue by nettyism** [ericsun977/equilibriumnj#23]
Physical Therapy at Equilibrium LLC incorporates a heavy emphasis on manual therapy by using advanced evaluative techniques to get to the root of the underlying problem. Each of our sessions are 60 minutes, one-on-one with a licensed Physical Therapist. This one-on-one time during each treatment session gives the Physical Therapist time to continuously evaluate and identify habits, postural inefficiencies, mechanical dysfunctions, strength deficits, faulty movement patterns that lead to pain and functional impairments. We find that patients respond quicker and better to treatments that are directed entirely by the Physical Therapist due to the individualized attention and manual facilitation during treatment sessions.

**Comment by ericwwsun** [comment]
This is published, please check @nettyism

**Comment by nettyism** [comment]
Thank you!
